import { createClient } from "@/lib/supabase/server";
import { fail, handleApiError, ok } from "@/lib/api/responses";
import { isPlatformResource, resourceRules, validatePayload } from "@/lib/validation/platform";
import { PlatformRepository } from "@/repositories/platform-repository";
type Context = { params: Promise<{ resource: string; id: string }> };
async function resolve(context: Context) { const { resource, id } = await context.params; if (!isPlatformResource(resource)) return null; return { resource, id, repository: new PlatformRepository(await createClient(), resource) }; }
const organizationId = (request: Request) => new URL(request.url).searchParams.get("organization_id");
export async function GET(request: Request, context: Context) { try { const value = await resolve(context), org = organizationId(request); if (!value) return fail("NOT_FOUND", "Unknown resource.", 404); if (!org) return fail("VALIDATION_ERROR", "organization_id is required.", 422); return ok(await value.repository.get(org, value.id)); } catch (error) { return handleApiError(error); } }
export async function PATCH(request: Request, context: Context) { try { const value = await resolve(context), org = organizationId(request); if (!value) return fail("NOT_FOUND", "Unknown resource.", 404); if (!org) return fail("VALIDATION_ERROR", "organization_id is required.", 422); const rule = resourceRules[value.resource]; if ("immutable" in rule && rule.immutable) return fail("IMMUTABLE_RESOURCE", "This resource is append-only.", 409); return ok(await value.repository.update(org, value.id, validatePayload(value.resource, await request.json(), "update"))); } catch (error) { return handleApiError(error); } }
export async function DELETE(request: Request, context: Context) { try { const value = await resolve(context), org = organizationId(request); if (!value) return fail("NOT_FOUND", "Unknown resource.", 404); if (!org) return fail("VALIDATION_ERROR", "organization_id is required.", 422); if (!(resourceRules[value.resource].writable as readonly string[]).includes("archived_at")) return fail("IMMUTABLE_RESOURCE", "This resource cannot be archived.", 409); return ok(await value.repository.archive(org, value.id)); } catch (error) { return handleApiError(error); } }
