"use client";
import { useMemo, useState } from "react";

const orders = [
  { id:"WO-1048",title:"Packaging line belt alignment",site:"North Plant · Line 3",owner:"Marcus Chen",initials:"MC",priority:"Critical",due:"Today, 10:30 AM",status:"In progress" },
  { id:"WO-1042",title:"Compressor pressure inspection",site:"North Plant · Utility Bay",owner:"Elena Ruiz",initials:"ER",priority:"High",due:"Today, 1:00 PM",status:"Scheduled" },
  { id:"WO-1039",title:"Loading dock door sensor",site:"West Hub · Dock 4",owner:"Jon Bell",initials:"JB",priority:"Medium",due:"Today, 3:30 PM",status:"In progress" },
  { id:"WO-1035",title:"Cold storage temperature audit",site:"West Hub · Zone B",owner:"Priya Shah",initials:"PS",priority:"High",due:"Tomorrow, 9:00 AM",status:"Scheduled" },
];
const nav = [["⌂","Overview"],["▣","Work orders"],["◇","Assets"],["▤","Inventory"],["◎","Team"]];
const metrics = [["▣","Open work orders","24","6 due today","coral"],["↗","Asset uptime","98.4%","+1.2% vs last week","green"],["◷","Avg. response time","18m","4m faster this month","blue"],["!","Inventory alerts","3","2 require action","amber"]];

export function Dashboard(){
 const [active,setActive]=useState("Overview"),[query,setQuery]=useState(""),[notice,setNotice]=useState(""),[menu,setMenu]=useState(false);
 const filtered=useMemo(()=>orders.filter(o=>Object.values(o).join(" ").toLowerCase().includes(query.toLowerCase())),[query]);
 function toast(message:string){setNotice(message);window.setTimeout(()=>setNotice(""),2400)}
 return <main className="shell">
  <aside className={`sidebar ${menu?"open":""}`}><div className="brand"><span>K</span>KOVE <b>OPS</b></div><p className="nav-label">Workspace</p><nav>{nav.map(([icon,label],i)=><button className={active===label?"nav active":"nav"} key={label} onClick={()=>{setActive(label);setMenu(false)}}><i>{icon}</i>{label}{i===1&&<em>12</em>}</button>)}</nav><p className="nav-label manage">Manage</p><button className="nav" onClick={()=>toast("Reports are ready to export")}><i>▥</i>Reports</button><button className="nav" onClick={()=>toast("Settings opened")}><i>⚙</i>Settings</button><div className="upgrade"><b>✦</b><strong>Unlock deeper insights</strong><p>Advanced reporting and forecasting for your whole operation.</p><button onClick={()=>toast("We’ll connect you with a KOVE specialist")}>Explore KOVE Pro</button></div><button className="profile" onClick={()=>toast("Profile menu opened")}><i className="avatar navy">AK</i><span><b>Alex Kim</b><small>Operations lead</small></span><em>•••</em></button></aside>
  <section className="workspace"><header className="topbar"><button className="hamburger" onClick={()=>setMenu(!menu)}>☰</button><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search work orders, assets, or people…"/></label><div className="top-actions"><button onClick={()=>toast("Help center opened")}>?</button><button onClick={()=>toast("You have 3 new notifications")}>♢<i/></button><span/><button className="site" onClick={()=>toast("Site switcher opened")}><i>N</i><span><small>Current site</small><b>North Plant</b></span>⌄</button></div></header>
   <div className="content"><div className="heading"><div><p>Sunday, July 19</p><h1>{active==="Overview"?"Good evening, Alex.":active}</h1><small>Here’s what’s happening across your operation.</small></div><button className="primary" onClick={()=>toast("New work order started")}>＋ <span>Create work order</span></button></div>
    <section className="metrics">{metrics.map(([icon,label,value,delta,tone])=><article key={label}><i className={tone}>{icon}</i><div><p>{label}</p><strong>{value}</strong><small>{delta}</small></div></article>)}</section>
    <div className="grid"><section className="panel work"><header><div><h2>Priority work</h2><p>Work orders that need your attention</p></div><button onClick={()=>setActive("Work orders")}>View all →</button></header><div className="order-head"><span>Work order</span><span>Assignee</span><span>Priority</span><span>Due</span><span>Status</span></div>{filtered.length?filtered.map(o=><button className="order" key={o.id} onClick={()=>toast(`${o.id} opened`)}><span><b>{o.title}</b><small>{o.id} · {o.site}</small></span><span className="person"><i className={`avatar ${o.initials.toLowerCase()}`}>{o.initials}</i>{o.owner}</span><span><em className={`priority ${o.priority.toLowerCase()}`}>{o.priority}</em></span><span className="due">{o.due}</span><span><em className={`status ${o.status==="In progress"?"progress":""}`}>● {o.status}</em></span></button>):<div className="empty">No work orders match “{query}”.</div>}</section>
     <aside className="sidepanels"><section className="panel health"><header><div><h2>Operational health</h2><p>Performance across all systems</p></div><select aria-label="Time range"><option>This week</option><option>Last week</option><option>This month</option></select></header><div className="score"><i><span>92<small>/100</small></span></i><div><b>Excellent</b><p>All critical systems are performing within target.</p></div></div>{[["Preventive maintenance","96%","green"],["Work order completion","89%","blue"],["Inventory availability","91%","amber"]].map(([label,n,tone])=><div className="bar" key={label}><span><i className={tone}/>{label}</span><b>{n}</b><div><i className={tone} style={{width:n}}/></div></div>)}</section>
      <section className="panel activity"><header><div><h2>Live activity</h2><p>Updates from your team</p></div><em>● Live</em></header>{[["ER","Elena completed WO-1028","Conveyor motor replacement","8 min ago"],["MC","Marcus added an update","WO-1048 · Belt alignment","21 min ago"],["PS","Priya flagged low stock","Temperature sensor · 3 remaining","42 min ago"]].map(([a,b,c,d])=><div className="activity-row" key={b}><i className={`avatar ${a.toLowerCase()}`}>{a}</i><div><b>{b}</b><p>{c}</p><small>{d}</small></div></div>)}</section></aside>
    </div></div>
  </section>{menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="Close menu"/>}{notice&&<div className="toast">✓ {notice}</div>}
 </main>
}
